name: chaardham
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  smooth_page_indicator: ^0.1.5
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0

  tab_indicator_styler: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/drawer.png
    - assets/images/search.png
    - assets/images/location.png
    - assets/images/kedarnath.jpg
    - assets/images/temple.png
    - assets/images/homegrey.png
    - assets/images/homeblack.png
    - assets/images/like.png
    - assets/images/backbutton.png
    - assets/images1/adventure.png
    - assets/images1/destination.png
    - assets/images1/events.png
    - assets/images1/festival.png
    - assets/images1/rafting.jpg
    - assets/images1/raftingb.jpg
    - assets/images1/trekkingf.jpg
    - assets/images1/trekkingb.jpg
    - assets/images1/paraf.jpg
    - assets/images1/parab.jpg
    - assets/images1/abbottb.jpg
    - assets/images1/abbottf.jpg
    - assets/images1/Chambab.jpg
    - assets/images1/Chambaf.jpg
    - assets/images1/Corbettb.jpg
    - assets/images1/Corbettf.jpg
    - assets/images1/Bissub.jpg
    - assets/images1/Bissuf.jpg
    - assets/images1/Devidhurab.jpg
    - assets/images1/Devidhuraf.jpg
    - assets/images1/Hilljatrab.jpg
    - assets/images1/Hilljatraf.jpg
    - assets/images2/aloha.jpg
    - assets/images2/manu.jpg
    - assets/images2/naini.jpg
    - assets/images2/raga.jpg
    - assets/images2/shervani.jpg
    - assets/images2/default.png










